### ISSUE TITLE
How do I install Solar Patcher?

### ISSUE THREAD

**Issue by Comicly69** [Solar-Tweaks/SolarPatcher#4]

**Comment by VytskaLT** [comment]
Read the usage part of the README. I'm pretty sure you can't do that in the official launcher. I use https://github.com/Nilsen84/lunar-client-qt

**Comment by 770grappenmaker** [comment]
First, install a third party launcher, like lunar client qt, or lunar client lite. This step is required right now because the launcher is not out yet. Then, download solar patcher from the [Releases page](https://github.com/Solar-Tweaks/SolarPatcher/releases). Then, add to the JVM arguments `-javaagent:/path/to/solar-patcher.jar`, where you of course replace it with the correct path. If you want to configure it, just tell me and I'll explain that as well, though you probably only want to use the packs fix, and this step is optional as well.

**Comment by bestdeveloperforever** [comment]
@770grappenmaker btw i did everything you said and still crashing what's wrong?

**Comment by 770grappenmaker** [comment]
Probably means you made an error in the argument you added: you can make things easier by adding it through lcqt's agent system, this does mean you cannot configure the agent.

**Comment by bestdeveloperforever** [comment]
i lunched it with LCL but what's the custom JVM arguments for the config json?

**Comment by 770grappenmaker** [comment]
If you want to specify a config, use the following argument: `-javaagent:/path/to/solar-patcher.jar=/path/to/config.json`, where the config.json file is a modified version of [this file](https://github.com/Solar-Tweaks/SolarPatcher/blob/main/config.example.json).

**Comment by 770grappenmaker** [comment]
@Comicly69 Do you still have a problem with installing? Closing in 7 days if I get no response.

**Comment by Comicly69** [comment]
Yep thanks this solved my problem

**Comment by 770grappenmaker** [comment]
Allright glad I could help

**Comment by narwhalito** [comment]
I added the arguments " -javaagent:/C:\Users\Cruzito\Documents\solar patcher/to/solar-patcher.jar=/C:\Users\Cruzito\Documents\solar patcher/to/config.json" but it still doesnt work when i press launch, im using lunar qt

**Comment by 770grappenmaker** [comment]
@narwhalito You messed up the path; try `-javaagent:C:\Users\narwhal\Documents\solar patcher\solar-patcher.jar=C:\Users\narwhal\Documents\solar patcher\config.json` (I think that is correct)
